"use client";

import { jsPDF } from "jspdf";
import type { ReferralNote } from "@/lib/types";

function lines(label: string, values: string[]) {
  if (!values.length) {
    return `${label}: None reported`;
  }
  return `${label}: ${values.join(", ")}`;
}

export function ReferralPdfButton({
  note,
  filename,
}: {
  note: ReferralNote;
  filename: string;
}) {
  function handleExport() {
    const doc = new jsPDF();
    const fullText = [
      "MaxWell Referral Note",
      `Generated: ${new Date(note.generatedAt).toLocaleString()}`,
      `Conversation ID: ${note.conversationId}`,
      "",
      `Age: ${note.patientBasics.age ?? "Unknown"}`,
      `Sex at birth: ${note.patientBasics.sexAtBirth}`,
      `Location: ${note.patientBasics.location}`,
      "",
      `Triage level: ${note.triageLevel.toUpperCase()}`,
      `Recommended urgency: ${note.recommendedUrgency}`,
      "",
      `Symptoms timeline: ${note.symptomsTimeline}`,
      lines("Red flags", note.redFlagsChecked),
      lines("Medications taken", note.medicationsTaken),
      lines("Allergies", note.allergies),
      lines("Suggested tests", note.suggestedTests),
      "",
      "Suspected conditions:",
      ...note.suspectedConditions.map(
        (entry) =>
          `- ${entry.condition} (${entry.likelihood}) | ${entry.rationale}`,
      ),
      "",
      `Vitals: Temp ${note.vitalsReported.temperatureC ?? "n/a"} C, Pulse ${note.vitalsReported.pulseBpm ?? "n/a"}, SpO2 ${note.vitalsReported.spo2 ?? "n/a"}, BP ${note.vitalsReported.bpSystolic ?? "n/a"}/${note.vitalsReported.bpDiastolic ?? "n/a"}`,
      "",
      `Doctor handoff summary: ${note.doctorHandoffSummary}`,
      "",
      "This note is generated by MaxWell for triage support and is not a definitive diagnosis.",
    ].join("\n");

    const wrapped = doc.splitTextToSize(fullText, 180);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(wrapped, 14, 16);
    doc.save(filename);
  }

  return (
    <button
      type="button"
      onClick={handleExport}
      className="rounded-full border border-cyan-200/35 px-3 py-1.5 text-xs font-medium text-cyan-100 hover:border-cyan-100/60"
    >
      Export PDF
    </button>
  );
}
